#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: #@ data.values.NAMESPACE
stringData:
  spring.datasource.url: #@ "jdbc:postgresql://{}/{}".format(data.values.DATABASE_NAME, data.values.DATABASE_NAME)
  spring.datasource.username: pgadmin
