#@ load("@ytt:data", "data")
#@ load("helpers.star", "labels_for_component")
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: #@ data.values.NAMESPACE
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector: #@ labels_for_component("frontend")
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: #@ data.values.NAMESPACE
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector: #@ labels_for_component("backend")
